name: DailyTracker
version: 1.0.0
main: com.niranjan0.dailytracker.DailyTracker
author: Niranjan0
api-version: 1.21
softdepend: [PlaceholderAPI, Essentials]

commands:
  dat:
    description: Main command for DailyTracker
    usage: /<command> <subcommand>
    aliases: [dailytracker, dt]

permissions:
  dailytracker.use:
    description: Allows player to view their own stats
    default: true
  dailytracker.admin:
    description: Allows player to view others stats and reload plugin
    default: true
  dailytracker.admin.downtime:
    description: Allows player to view/reset downtime
    default: true