name: DailyTracker
version: '${project.version}'
main: com.niranjan0.dailytracker.DailyTracker
api-version: 1.21
author: Niranjan0
description: Track player uptime and server downtime
website: https://github.com/Niranjan0
depend: [PlaceholderAPI]

commands:
  dat:
    description: Main DailyTracker command
    usage: /dat <stats|top|history|downtime|reload> [args...]
    permission: dailytracker.use

permissions:
  dailytracker.use:
    description: Allows viewing own stats
    default: true
  dailytracker.admin:
    description: Allows viewing others' stats and reload plugin
    default: op
  dailytracker.admin.downtime:
    description: Allows managing server downtime
    default: op